//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniPsg.Model.PAS.Assess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public int Code { get; set; }
        public string Name { get; set; }
        public string Definition { get; set; }
        public int ViewStarDate { get; set; }
        public int ViewEndDate { get; set; }
        public int FromDate { get; set; }
        public int Deadline { get; set; }
        public int AssessYear { get; set; }
        public int CategoryCode { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Modifier { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
